version: '3'
services:

  opensearch:
    hostname: opensearch
    image: opensearchproject/opensearch:2.8.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    networks:
      - net1

  opensearch-dashboard:
    hostname: opensearch-dashboard
    image: opensearchproject/opensearch-dashboards:2.8.0
    links:
      - opensearch
    ports:
      - "5601:5601"
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch:9200"]'
    depends_on:
      - opensearch
    networks:
      - net1

  logstash:
    hostname: logstash
    image: opensearchproject/logstash-oss-with-opensearch-output-plugin:8.6.1
    links:
      - opensearch
    volumes:
      - ${PWD}/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "9125:9125/udp"
    depends_on:
      - opensearch
    networks:
      - net1

  accounts:
    hostname: accounts
    environment:
      - ACCOUNTS_HOST=accounts
      - TRANSFERS_HOST=transfers
      - STATEMENTS_HOST=statements
      - LOGSTASH_HOST=logstash
      - OPENSEARCH_DASHBOARD_HOST=opensearch-dashboard
    build: ../accounts/
    command: ["deploy-with-elk"]
    depends_on:
      - logstash
    ports:
      - "8000:8000"
    networks:
      - net1

  transfers:
    hostname: transfers
    environment:
      - ACCOUNTS_HOST=accounts
      - TRANSFERS_HOST=transfers
      - STATEMENTS_HOST=statements
      - LOGSTASH_HOST=logstash
      - OPENSEARCH_DASHBOARD_HOST=opensearch-dashboard
    command: ["deploy-with-elk"]
    build: ../transfers/
    depends_on:
      - accounts
      - logstash
    ports:
      - "8001:8001"
    networks:
      - net1

  statements:
    hostname: statements
    environment:
      - ACCOUNTS_HOST=accounts
      - TRANSFERS_HOST=transfers
      - STATEMENTS_HOST=statements
      - LOGSTASH_HOST=logstash
      - OPENSEARCH_DASHBOARD_HOST=opensearch-dashboard
    command: ["deploy-with-elk"]
    build: ../statements/
    depends_on:
      - transfers
      - logstash
    ports:
      - "8002:8002"
    networks:
      - net1

  nginx:
    hostname: nginx
    environment:
      - ACCOUNTS_HOST=accounts
      - TRANSFERS_HOST=transfers
      - STATEMENTS_HOST=statements
    image: nginx:latest
    volumes:
      - ../nginx/:/usr/share/nginx/
      - ../nginx/sites-enabled/:/etc/nginx/conf.d/
    ports:
      - 8080:80
      - 443:443
    depends_on:
      - accounts
      - transfers
      - statements
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    networks:
      - net1

networks:
  net1:
    driver: bridge
