version: '3'
services:

  elasticsearch:
    hostname: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.3
    volumes:
      - ${PWD}/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
    networks:
      - net1

  kibana:
    hostname: kibana
    build:
      context: .
      dockerfile: kibana-dockerfile
    links:
      - elasticsearch
    volumes:
      - ${PWD}/kibana.yml:/etc/kibana/kibana.yml
      - ${PWD}/logtrail.json:/usr/share/kibana/plugins/logtrail/logtrail.json
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - net1


  logstash:
    hostname: logstash
    image: docker.elastic.co/logstash/logstash-oss:6.1.3
    links:
      - elasticsearch
    volumes:
      - ${PWD}/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "9125:9125/udp"
    depends_on:
      - elasticsearch
    networks:
      - net1

  accounts:
    hostname: accounts
    environment: 
      - ACCOUNTS_HOST=accounts
      - TRANSFERS_HOST=transfers
      - BANK_STATEMENTS_HOST=bank-statements
      - LOGSTASH_HOST=logstash
      - KIBANA_HOST=kibana
    build: ../accounts/
    command: ["deploy-with-elk"]
    depends_on:
      - logstash
    ports:
      - "8000:8000"
    networks:
      - net1

  transfers:
    hostname: transfers
    environment: 
      - ACCOUNTS_HOST=accounts
      - TRANSFERS_HOST=transfers
      - BANK_STATEMENTS_HOST=bank-statements
      - LOGSTASH_HOST=logstash
      - KIBANA_HOST=kibana
    command: ["deploy-with-elk"]
    build: ../transfers/
    depends_on:
      - accounts
      - logstash
    ports:
      - "8001:8001"
    networks:
      - net1

  bank_statements:
    hostname: bank-statements
    environment: 
      - ACCOUNTS_HOST=accounts
      - TRANSFERS_HOST=transfers
      - BANK_STATEMENTS_HOST=bank-statements
      - LOGSTASH_HOST=logstash
      - KIBANA_HOST=kibana
    command: ["deploy-with-elk"]
    build: ../bank_statements/
    depends_on:
      - transfers
      - logstash
    ports:
      - "8002:8002"
    networks:
      - net1

  nginx:
    hostname: nginx
    environment: 
      - ACCOUNTS_HOST=accounts
      - TRANSFERS_HOST=transfers
      - BANK_STATEMENTS_HOST=bank-statements
    image: nginx:latest
    volumes:
      - ../nginx/:/usr/share/nginx/
      - ../nginx/sites-enabled/:/etc/nginx/conf.d/
    ports:
      - 8080:80
      - 443:443
    depends_on:
      - accounts
      - transfers
      - bank_statements
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    networks:
      - net1

networks:
  net1:
    driver: bridge
